// <auto-generated />
namespace TrafficPolice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class lastfixDTP1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lastfixDTP1));
        
        string IMigrationMetadata.Id
        {
            get { return "202105282222418_lastfixDTP1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
